name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - tests # revert once tests are done
  workflow_dispatch:
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run tests
        env:
          CI: true
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          
          MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
          MQTT_PORT: ${{ secrets.MQTT_PORT }}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          MQTT_CLIENT_ID: ${{ secrets.MQTT_CLIENT_ID }}
          MQTT_SUBSCRIBE_TOPIC: ${{ secrets.MQTT_SUBSCRIBE_TOPIC }}
          MQTT_PUBLISH_TOPIC: ${{ secrets.MQTT_PUBLISH_TOPIC }}
        run: cd Tests && dotnet test